<?php
// Migration script — ARISE Platform — 2026-05-11
// Self-deletes after execution. Safe to run multiple times (idempotent).

$dbPath = '/home/cpmsfdav/public_html/arise/data/arise.db';
if (!file_exists($dbPath)) {
    $dbPath = __DIR__ . '/data/arise.db';
}

$results = [];
$errors  = [];

function ok(string $msg): string {
    return '<li style="color:#1a7a1a">&#10003; ' . htmlspecialchars($msg) . '</li>';
}
function fail(string $msg): string {
    return '<li style="color:#a00">&#10007; ' . htmlspecialchars($msg) . '</li>';
}

try {
    if (!file_exists($dbPath)) {
        throw new Exception("Database not found at: $dbPath");
    }

    $db = new SQLite3($dbPath);
    $db->enableExceptions(true);
    $db->exec('PRAGMA journal_mode=WAL;');
    $db->exec('PRAGMA foreign_keys=OFF;');

    // -------------------------------------------------------------------------
    // STEP 1 — Remove old test/empty modules 12–16
    // -------------------------------------------------------------------------
    $db->exec('DELETE FROM quiz_questions WHERE module_id IN (12,13,14,15,16);');
    $db->exec('DELETE FROM lessons WHERE module_id IN (12,13,14,15,16);');
    $db->exec('DELETE FROM modules WHERE id IN (12,13,14,15,16);');
    $results[] = ok('Step 1: Deleted quiz_questions, lessons, and modules for IDs 12–16');

    // -------------------------------------------------------------------------
    // STEP 2 — Create module 21 if not exists
    // -------------------------------------------------------------------------
    $db->exec("INSERT OR IGNORE INTO modules (id, title, slug, description, icon, sort_order, is_active)
        VALUES (21, 'Biblical Foundation on Sexuality', 'biblical-sexuality',
        'Exploring what the Bible teaches about sexuality, purity, relationships, and God''s design for human intimacy.',
        'cross', 21, 1);");
    $mod21 = $db->querySingle("SELECT id FROM modules WHERE id=21");
    if ($mod21 == 21) {
        $results[] = ok('Step 2: Module 21 (Biblical Foundation on Sexuality) exists');
    } else {
        $errors[] = fail('Step 2: Module 21 not found after INSERT OR IGNORE');
    }

    // -------------------------------------------------------------------------
    // STEP 3 — Update video lesson file_paths
    // -------------------------------------------------------------------------
    $videoUpdates = [
        24 => 'videos/arise_drug_abuse.mp4',
        36 => 'videos/arise_healthy_relationships.mp4',
        27 => 'videos/arise_abstinence.mp4',
        38 => 'videos/arise_stds.mp4',
        28 => 'videos/arise_adolescent_growth.mp4',
        39 => 'videos/arise_social_media_srh.mp4',
        40 => 'videos/arise_uti.mp4',
        37 => 'videos/arise_mental_health.mp4',
        41 => 'videos/arise_gambling.mp4',
        43 => 'videos/arise_career_decisions.mp4',
        44 => 'videos/arise_cyber_crimes.mp4',
    ];
    $updated = 0;
    foreach ($videoUpdates as $id => $path) {
        $db->exec("UPDATE lessons SET file_path='" . $db->escapeString($path) . "' WHERE id=" . (int)$id . ";");
        $updated++;
    }
    $results[] = ok("Step 3: Updated $updated video lesson file_paths to new arise_*.mp4 names");

    // -------------------------------------------------------------------------
    // STEP 4 — Delete orphaned lesson records
    // -------------------------------------------------------------------------
    $db->exec('DELETE FROM lessons WHERE id IN (23,25,26);');
    $results[] = ok('Step 4: Deleted orphaned lesson records id IN (23,25,26)');

    // -------------------------------------------------------------------------
    // STEP 5 — Insert new lesson records (INSERT OR IGNORE with explicit IDs)
    // -------------------------------------------------------------------------
    // (id, module_id, title, slug, lesson_type, file_path, sort_order, is_active, is_published)
    $newLessons = [
        [47, 17, 'Female Genital Mutilation', 'fgm-video', 'video', 'videos/arise_fgm.mp4', 1, 1, 1],
        [48, 6,  'Life Skills', 'life-skills-video', 'video', 'videos/arise_life_skills.mp4', 0, 1, 1],
        [49, 18, 'The Reality of Gambling', 'gambling-interactive', 'interactive', 'interactive/lesson-24-gambling.html', 2, 1, 1],
        [50, 20, 'Cyber Crimes — Online Safety & Digital Rights', 'cyber-crimes-interactive', 'interactive', 'interactive/lesson-25-cyber-crimes.html', 2, 1, 1],
        [51, 19, 'Career Decisions — Planning Your Future', 'career-decisions-interactive', 'interactive', 'interactive/lesson-26-career-decisions.html', 2, 1, 1],
        [52, 21, 'Biblical Foundation on Sexuality', 'biblical-sexuality-interactive', 'interactive', 'interactive/lesson-27-biblical-sexuality.html', 1, 1, 1],
        [53, 21, 'Biblical Foundation on Sexuality', 'biblical-sexuality-video', 'video', 'videos/arise_biblical_sexuality.mp4', 2, 1, 1],
    ];
    $insertedLessons = 0;
    foreach ($newLessons as $l) {
        $db->exec("INSERT OR IGNORE INTO lessons
            (id, module_id, title, slug, lesson_type, file_path, sort_order, is_active, is_published)
            VALUES (
                " . (int)$l[0] . ",
                " . (int)$l[1] . ",
                '" . $db->escapeString($l[2]) . "',
                '" . $db->escapeString($l[3]) . "',
                '" . $db->escapeString($l[4]) . "',
                '" . $db->escapeString($l[5]) . "',
                " . (int)$l[6] . ",
                " . (int)$l[7] . ",
                " . (int)$l[8] . "
            );");
        $insertedLessons++;
    }
    $results[] = ok("Step 5: Inserted $insertedLessons new lesson records (INSERT OR IGNORE)");

    // -------------------------------------------------------------------------
    // STEP 6 — Publish unpublished lessons
    // -------------------------------------------------------------------------
    $db->exec('UPDATE lessons SET is_published=1 WHERE id IN (6,27,45,46);');
    $results[] = ok('Step 6: Set is_published=1 for lessons id IN (6,27,45,46)');

    // -------------------------------------------------------------------------
    // STEP 7 — Insert quiz questions per module, only if count=0 for that module+section
    // -------------------------------------------------------------------------
    // Questions are grouped by module_id and section.
    // Format: [module_id, question_type, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, sort_order, section, competency, difficulty]

    $allQuestions = [

        // ---- MODULE 11 — pre ----
        [11,'mcq','Amina, a Form 3 student in Nairobi, tells her friend she has been feeling very sad and empty for the past three weeks and has lost interest in activities she used to enjoy. Which term best describes what Amina may be experiencing?','Normal exam stress','Clinical depression','Peer pressure','Physical exhaustion','','B','Clinical depression is characterised by persistent low mood lasting two weeks or more, along with loss of interest in previously enjoyable activities (anhedonia). Amina\'s symptoms match this description.',1,'pre','mental_health','MEDIUM'],
        [11,'msq','Which of the following are recognised warning signs that a young person in Kenya may be at risk of suicide? Select ALL that apply.','Talking about wanting to die or feeling hopeless','Giving away treasured personal possessions','Studying harder than usual for KCSE','Extreme withdrawal from friends and family','Expressing that others would be better off without them','A,B,D,E','Key crisis warning signs include talking about death or hopelessness, giving away possessions, withdrawing from social contact, and expressing that one is a burden. Studying harder is a normal coping behaviour, not a warning sign.',2,'pre','mental_health','MEDIUM'],
        [11,'mcq','The World Health Organization defines mental health as a state of wellbeing in which a person realises their own potential, can cope with normal stresses, and can contribute to their community. What does this definition emphasise?','Mental health is only about the absence of mental illness','Mental health is a positive state of wellbeing, not just the absence of illness','Mental health only matters for adults','Mental health problems only affect people in cities like Nairobi','','B','The WHO definition emphasises that mental health is a positive state of wellbeing. A person can be mentally healthy even when facing challenges, and mental illness is not the only measure of poor mental health.',3,'pre','mental_health','MEDIUM'],
        [11,'msq','Hassan is a Form 4 student in Mombasa preparing for KCSE. Which of the following are examples of healthy ways to manage stress? Select ALL that apply.','Regular physical exercise such as running or football','Talking to a trusted friend, teacher, or counsellor','Using alcohol or miraa to feel relaxed','Getting adequate sleep each night','Practising deep breathing or relaxation techniques','A,B,D,E','Exercise, social support, adequate sleep, and relaxation techniques are all evidence-based strategies for managing stress. Using alcohol or miraa is harmful and worsens mental health outcomes.',4,'pre','mental_health','MEDIUM'],
        [11,'mcq','In Kenya, one of the biggest barriers that stops young people from seeking help for mental health problems is:','Lack of mobile phones to call helplines','Stigma and fear of being judged or labelled as crazy','The high cost of speaking to a friend','Schools providing too many counsellors','','B','Stigma — the fear of being judged, labelled, or discriminated against — is widely recognised as the primary barrier to mental health help-seeking in Kenya and across Africa.',5,'pre','mental_health','MEDIUM'],

        // ---- MODULE 11 — lesson ----
        [11,'msq','According to the WHO definition discussed in the lesson, which of the following are components of good mental health? Select ALL that apply.','Realising one\'s own potential and abilities','Coping with the normal stresses of life','Never feeling sad, angry, or anxious at any time','Contributing productively to one\'s community','Having positive relationships and connections with others','A,B,D,E','WHO defines mental health as wellbeing encompassing potential, coping, productivity, and community contribution. Feeling negative emotions is normal and does not indicate poor mental health — their absence is not required.',1,'lesson','mental_health','MEDIUM'],
        [11,'mcq','Grace is a facilitator running a session in Kisumu. A student asks: what is the difference between normal stress and a mental health disorder? Grace\'s BEST answer is:','They are exactly the same thing','Normal stress is brief and manageable; a disorder is persistent, severe, and significantly disrupts daily life','Mental health disorders only affect adults, not students','Normal stress is caused by exams while disorders are caused by family problems','','B','Normal stress is a temporary response to a specific challenge and resolves when the stressor passes. Mental health disorders such as depression or anxiety are persistent, more severe, and significantly impair a person\'s ability to function in daily life.',2,'lesson','mental_health','MEDIUM'],
        [11,'msq','Lydia, a Form 2 student in Nakuru, was involved in a serious road accident six months ago. She now has recurring nightmares, avoids matatus, feels constantly on edge, and relives the accident as if it is happening again. Which symptoms are consistent with Post-Traumatic Stress Disorder (PTSD)? Select ALL that apply.','Recurring nightmares related to the traumatic event','Flashbacks where she relives the accident','Avoidance of things that remind her of the trauma','Improved concentration and better school performance','Hypervigilance — feeling constantly on alert or jumpy','A,B,C,E','PTSD symptoms include flashbacks, nightmares, avoidance of trauma reminders, and hypervigilance. Improved concentration and school performance are not associated with PTSD — the disorder typically impairs concentration and academic functioning.',3,'lesson','mental_health','MEDIUM'],
        [11,'mcq','When the body exercises, it releases chemicals that improve mood and reduce feelings of stress and anxiety. What are these chemicals called?','Adrenaline','Cortisol','Endorphins','Insulin','','C','Endorphins are natural chemicals released by the brain during physical exercise. They act as natural pain-relievers and mood-lifters, which is why regular exercise is recommended as part of mental health self-care.',4,'lesson','mental_health','MEDIUM'],
        [11,'msq','Brian, a peer educator in Eldoret, is teaching fellow students to recognise clinical depression. Which of the following are core symptoms of clinical depression? Select ALL that apply.','Persistent low mood or sadness lasting two weeks or more','Loss of interest or pleasure in activities once enjoyed','Feeling energised and sleeping much less than usual','Persistent fatigue and low energy','Feelings of worthlessness or excessive guilt','A,B,D,E','Clinical depression is characterised by persistent low mood (at least 2 weeks), anhedonia, fatigue, and feelings of worthlessness. Feeling energised and sleeping less is a feature of mania, not depression.',5,'lesson','mental_health','MEDIUM'],
        [11,'mcq','Fatuma, a counsellor at a school in Garissa, explains that anxiety disorders differ from normal anxiety because they involve:','Feeling nervous before an important football match','Fear that is excessive, persistent, and not proportionate to the actual situation','Worrying about KCSE results for one day and then feeling fine','Short-term nervousness when meeting new people','','B','Anxiety disorders involve fear or worry that is excessive, persistent, and out of proportion to the actual threat. Normal anxiety is temporary and situation-specific, whereas anxiety disorders significantly interfere with daily functioning.',6,'lesson','mental_health','MEDIUM'],
        [11,'msq','Peter, a Form 3 student in Thika, tells a classmate he is thinking about ending his life. Which of the following are the correct immediate responses? Select ALL that apply.','Stay with Peter and do not leave him alone','Tell a trusted adult such as a teacher or counsellor immediately','Tell Peter to stop being dramatic and go back to class','Listen to Peter calmly and take what he says seriously','Help connect Peter to Befrienders Kenya on 0722 178 177','A,B,D,E','When someone expresses suicidal ideation you must: stay with them, listen without dismissing, take it seriously, and immediately involve a trusted adult and professional support. Dismissing suicidal talk is dangerous and never appropriate.',7,'lesson','mental_health','MEDIUM'],
        [11,'mcq','Kenya has approximately one psychiatrist per one million people. What does this statistic most directly highlight?','Kenyans do not need mental health professionals','There is a severe shortage of mental health specialists in Kenya','Mental health disorders are very rare in Kenya','Community health workers are more common than psychiatrists everywhere in the world','','B','Kenya\'s ratio of roughly one psychiatrist per one million people reflects one of the most severe mental health workforce shortages globally. This shortage makes community-based support, peer education, and helplines especially important.',8,'lesson','mental_health','MEDIUM'],
        [11,'msq','A facilitator in Kisii is teaching students about Kenyan mental health resources. Which of the following statements about these resources are CORRECT? Select ALL that apply.','Befrienders Kenya can be reached on 0722 178 177 and provides 24-hour suicide prevention support','Childline 116 is a free helpline available to children and young people in crisis','NACADA\'s toll-free line 0800 723 253 provides support for drug abuse and mental health concerns','You must pay a consultation fee before Befrienders Kenya will speak with you','Mental health helplines in Kenya provide a first point of contact before professional referral','A,B,C,E','Befrienders Kenya (0722 178 177) operates 24 hours at no cost; Childline 116 is free for youth; NACADA 0800 723 253 is toll-free. All serve as important first points of contact. Paying a consultation fee before speaking with Befrienders is false.',9,'lesson','mental_health','MEDIUM'],
        [11,'mcq','Research estimates that approximately what proportion of Kenyans will experience a mental health condition at some point in their lifetime?','About 5%','About 10%','About 25%','About 60%','','C','Studies indicate that approximately 25% of Kenyans — one in four — will experience a mental health condition during their lifetime. This underscores the importance of mental health education and accessible support services.',10,'lesson','mental_health','MEDIUM'],

        // ---- MODULE 11 — post ----
        [11,'mcq','Zawadi, a Form 4 student in Siaya, has been persistently sad for three weeks, stopped attending choir which she loved, and says she feels empty inside. Her friend Miriam wants to help. What is the MOST appropriate first step for Miriam to take?','Tell Zawadi to pray harder and she will feel better','Listen to Zawadi without judgement and encourage her to speak to the school counsellor','Post about Zawadi\'s problems on social media to get community support','Tell Zawadi that everyone feels sad sometimes and she should move on','','B','The best first response is to listen without judgement and support the person in accessing professional help. Zawadi\'s symptoms (persistent sadness at least 2 weeks, anhedonia) suggest clinical depression, which requires professional involvement.',1,'post','mental_health','MEDIUM'],
        [11,'msq','Kevin is a peer educator in Meru. A classmate asks which physical symptoms can be associated with anxiety disorders. Which of the following should Kevin include? Select ALL that apply.','Rapid heartbeat or palpitations','Shortness of breath or chest tightness','Persistent low mood lasting more than two weeks','Sweating, trembling, or shaking','Dizziness or feeling faint','A,B,D,E','Physical symptoms of anxiety disorders include rapid heartbeat, shortness of breath, sweating, trembling, and dizziness. Persistent low mood for two weeks or more is a hallmark of depression, not anxiety disorder.',2,'post','mental_health','MEDIUM'],
        [11,'mcq','A school counsellor in Nakuru is discussing mental health stigma with Form 3 students. Which statement BEST describes why stigma is harmful?','Stigma encourages people to seek professional help earlier','Stigma causes people to hide their symptoms and avoid seeking help, worsening their condition','Stigma only affects people who already have severe mental illness','Stigma is helpful because it motivates people to get better faster','','B','Stigma causes shame, fear of judgement, and social exclusion. This leads people to conceal their struggles and delay or avoid seeking help, which allows mental health conditions to worsen. Addressing stigma is a critical public health priority in Kenya.',3,'post','mental_health','MEDIUM'],
        [11,'msq','Hassan has just witnessed his close friend Peter give away his phone and school shoes and say everyone will be fine without him. Which of the following crisis warning signs is Peter displaying? Select ALL that apply.','Giving away prized possessions','Expressing that others would be better off without him','Working extra hard on his class assignments','Extreme withdrawal and saying goodbye to friends','Verbal expression of hopelessness about the future','A,B,D,E','Giving away possessions, expressing that one is a burden, withdrawing and saying goodbye, and hopelessness are all serious crisis warning signs requiring immediate action. Increased effort in class assignments is not a warning sign.',4,'post','mental_health','MEDIUM'],
        [11,'mcq','Amina in Nairobi regularly runs for 30 minutes after school and says it significantly lifts her mood. The lesson explains this is because exercise:','Distracts the brain so it forgets problems permanently','Triggers the release of endorphins, which are natural mood-lifting chemicals in the brain','Reduces the body\'s need for sleep, leaving more time to study','Increases cortisol levels which improve academic performance','','B','Exercise stimulates the brain to release endorphins — natural chemicals that reduce pain and elevate mood. This is one reason regular physical activity is recommended as part of mental health self-care for young people.',5,'post','mental_health','MEDIUM'],

        // ---- MODULE 17 — pre ----
        [17,'mcq','Amina, a Form 3 student in Garissa, hears classmates discussing a traditional ceremony involving cutting of girls. What is the correct term for procedures that involve partial or total removal of female genital organs for non-medical reasons?','Female genital mutilation (FGM)','Female circumcision surgery','Traditional genital therapy','Ritual cleansing procedure','','A','Female genital mutilation (FGM) is the WHO-recognised term for all procedures involving partial or total removal of or injury to the female genital organs for non-medical reasons. The term female circumcision is misleading and should not be used.',1,'pre','fgm_gbv','MEDIUM'],
        [17,'msq','Grace, a peer educator in Isiolo, is preparing a talk on FGM for her school. Which of the following are known immediate health consequences of FGM? Select ALL that apply.','Severe pain and bleeding','Urinary problems and retention','Increased fertility in later life','Serious infection and sepsis','Shock, which can lead to death','A,B,D,E','Immediate health consequences of FGM include severe pain, excessive bleeding, urinary problems, infection/sepsis, and shock that can result in death. FGM does NOT increase fertility — that is a harmful myth. There are no medical benefits to FGM.',2,'pre','fgm_gbv','MEDIUM'],
        [17,'mcq','Hassan, a Form 2 student in Marsabit, is told by an elder that FGM is a religious requirement in Islam. What is the correct response to this claim?','FGM is mandatory in Islam and is supported by the Quran','FGM is required by Islam only in certain counties of Kenya','No major religion, including Islam, mandates FGM','FGM is required by Christianity but not Islam','','C','No major religion mandates FGM. Neither Islam, Christianity, nor any other widely practised faith requires FGM. Religious leaders across faiths have spoken out against the practice. This is one of the most common myths used to justify FGM.',3,'pre','fgm_gbv','MEDIUM'],
        [17,'msq','Zawadi, a Form 4 student in Nairobi, is researching communities most affected by FGM in Kenya. Which of the following counties have some of the highest FGM prevalence rates in Kenya? Select ALL that apply.','Marsabit','Isiolo','Mombasa','Garissa','Samburu','A,B,D,E','According to the KDHS 2022, counties with the highest FGM prevalence include Marsabit, Isiolo, Garissa, Samburu, and Kajiado. Mombasa does not feature among the highest-prevalence counties.',4,'pre','fgm_gbv','MEDIUM'],
        [17,'mcq','Fatuma, a student in Meru, learns that FGM is illegal in Kenya. Under which law is FGM prohibited?','The Children Act of 2001','The Prohibition of Female Genital Mutilation Act of 2011','The Sexual Offences Act of 2006','The Public Health Act of 1986','','B','FGM is illegal in Kenya under the Prohibition of Female Genital Mutilation Act of 2011. This law makes it a criminal offence to practise, procure, or promote FGM, and it is punishable by imprisonment.',5,'pre','fgm_gbv','MEDIUM'],

        // ---- MODULE 17 — lesson ----
        [17,'msq','A health educator in Kisumu explains the WHO classification of FGM types. Which of the following correctly describe the four WHO types of FGM? Select ALL that apply.','Type I involves partial or total removal of the clitoris (clitoridectomy)','Type II involves removal of the clitoris and labia minora (excision)','Type III involves narrowing of the vaginal opening by cutting and stitching (infibulation)','Type IV includes all other harmful non-medical procedures to female genitalia','Type II involves removal of the outer skin of the abdomen','A,B,C,D','The WHO classifies FGM into four types: Type I (clitoridectomy), Type II (excision — clitoris and labia minora), Type III (infibulation — stitching to narrow the vaginal opening, the most severe type), and Type IV (all other harmful non-medical procedures). Option E is incorrect — Type II does not involve the abdomen.',1,'lesson','fgm_gbv','MEDIUM'],
        [17,'mcq','Nasrin, a Form 3 student in Isiolo, asks which type of FGM is the most severe. Her teacher explains it involves stitching to narrow the vaginal opening. Which WHO type is this?','Type I','Type II','Type IV','Type III','','D','Type III FGM, known as infibulation, is the most severe form. It involves cutting and stitching the vaginal opening leaving only a small opening for urine and menstrual flow. It causes the most serious health complications including obstructed labour.',2,'lesson','fgm_gbv','MEDIUM'],
        [17,'msq','Rehema, a peer educator in Garissa, is debunking myths about FGM. Which of the following are FALSE myths commonly used to justify FGM? Select ALL that apply.','FGM increases a woman\'s fertility','FGM is required by the Islamic faith','FGM prevents girls from being promiscuous','FGM makes childbirth safer for the mother','FGM has no health benefits and causes only harm','A,B,C,D','Options A through D are all false myths. FGM does not increase fertility, is not required by any religion, does not prevent promiscuity, and makes childbirth more dangerous — not safer. Option E is the factual statement: FGM has no health benefits and causes serious harm.',3,'lesson','fgm_gbv','MEDIUM'],
        [17,'mcq','Peter, a Form 4 student in Nakuru, learns that FGM violates several human rights. Which right is most directly violated when a girl is subjected to FGM without her consent?','The right to education','The right to vote','The right to bodily integrity and freedom from violence','The right to employment','','C','FGM directly violates the right to bodily integrity — the right to control what happens to one\'s own body — and the right to freedom from violence. It also violates the right to health, but bodily integrity is the most directly relevant right.',4,'lesson','fgm_gbv','MEDIUM'],
        [17,'msq','Miriam, a Form 2 student in Siaya, wants to report a planned FGM ceremony for her neighbour. Which of the following are valid ways to report FGM in Kenya? Select ALL that apply.','Call 116 (Childline Kenya)','Contact the nearest police station','Contact the local chief or assistant chief','Contact the Directorate of Children\'s Services','Stay silent to avoid community conflict','A,B,C,D','FGM can be reported by calling 116 (Childline Kenya), going to the nearest police station, contacting the local chief or assistant chief, or reaching the Directorate of Children\'s Services. Staying silent is never the right choice — reporting protects girls from serious harm.',5,'lesson','fgm_gbv','MEDIUM'],
        [17,'mcq','Aisha, a Form 3 student in Mombasa, learns about the legal penalty for performing FGM in Kenya. A practitioner is convicted of FGM that did NOT result in death. What is the maximum prison sentence?','Up to 1 year imprisonment','Up to 5 years imprisonment','Up to 3 years imprisonment','Up to 10 years imprisonment','','C','Under the Prohibition of Female Genital Mutilation Act 2011, a person convicted of performing FGM faces up to 3 years imprisonment. If the FGM results in the victim\'s death, the penalty increases to up to 7 years imprisonment.',6,'lesson','fgm_gbv','MEDIUM'],
        [17,'msq','Brian, a male ally in Eldoret, is helping his community move away from FGM. Which of the following are effective community-level strategies to end FGM? Select ALL that apply.','Engaging community and religious elders in dialogue','Introducing alternative rites of passage that celebrate girls without cutting','Educating boys and men to become allies against FGM','Educating girls and women about their rights and the harms of FGM','Continuing FGM but only using sterilised equipment to reduce infection','A,B,C,D','Effective strategies include engaging elders, introducing alternative rites of passage, mobilising male allies, and educating girls about their rights. Option E is dangerously wrong — there is no safe way to perform FGM, and medicalised FGM is also prohibited by WHO and Kenyan law.',7,'lesson','fgm_gbv','MEDIUM'],
        [17,'mcq','Lydia, a Form 4 student in Thika, is researching long-term health consequences of FGM. Which of the following is a recognised long-term consequence?','Improved sexual satisfaction due to heightened sensitivity','Obstructed labour and complications during childbirth','Reduced risk of urinary tract infections','Faster recovery from pregnancy','','B','Obstructed labour is one of the most serious long-term consequences of FGM, particularly Type III. Scar tissue narrows the birth canal causing dangerous complications. Other long-term consequences include fistula, chronic pain, PTSD, and sexual dysfunction. FGM has no health benefits.',8,'lesson','fgm_gbv','MEDIUM'],
        [17,'msq','Kevin, a Form 3 student in Kisii, asks about the long-term psychological and physical effects of FGM. Which of the following are recognised long-term consequences? Select ALL that apply.','Post-traumatic stress disorder (PTSD)','Chronic pelvic pain','Obstetric fistula','Sexual dysfunction and loss of sexual pleasure','Increased protection against sexually transmitted infections','A,B,C,D','Long-term consequences of FGM include PTSD, chronic pelvic pain, obstetric fistula (from obstructed labour), and sexual dysfunction. FGM does NOT protect against STIs — that is a dangerous myth. All four correct options (A to D) are medically documented harms of FGM.',9,'lesson','fgm_gbv','MEDIUM'],
        [17,'mcq','According to the Kenya Demographic and Health Survey 2022, approximately what percentage of Kenyan women have undergone FGM?','About 5%','About 50%','About 21%','About 75%','','C','The KDHS 2022 estimates approximately 21% of Kenyan women aged 15 to 49 have undergone FGM. While this represents a decline due to legal and educational efforts, FGM remains a serious public health concern especially in certain counties.',10,'lesson','fgm_gbv','MEDIUM'],

        // ---- MODULE 17 — post ----
        [17,'mcq','Nasrin in Isiolo describes a procedure where only the clitoral hood was removed but the clitoris itself is intact. Which WHO type does this fall under?','Type II','Type III','Type I','Type IV','','C','Type I FGM (clitoridectomy) includes partial or total removal of the clitoris and/or the prepuce (clitoral hood). Even partial removal of the clitoral hood falls under Type I. Type II involves the labia, Type III involves stitching, and Type IV covers other harmful procedures.',1,'post','fgm_gbv','MEDIUM'],
        [17,'msq','Nasrin\'s younger sister in Isiolo is at risk of FGM. Which of the following actions would be appropriate for Nasrin to take? Select ALL that apply.','Call 116 (Childline Kenya) to report the threat','Inform a trusted teacher or school counsellor','Contact the local assistant chief for intervention','Reach out to the Directorate of Children\'s Services','Keep quiet to respect cultural traditions and avoid conflict','A,B,C,D','When a girl is at risk of FGM, appropriate actions include calling Childline (116), informing a trusted adult at school, contacting the local chief, or reaching the Directorate of Children\'s Services. Staying silent allows harm to happen and contravenes the duty to report under the Prohibition of FGM Act 2011.',2,'post','fgm_gbv','MEDIUM'],
        [17,'mcq','A community health worker in Marsabit is counselling a family who believe FGM will improve their daughter\'s marriage prospects. What is the most accurate and rights-based response?','FGM may be acceptable if the girl consents when she is older','FGM is illegal in Kenya, causes serious health harm, and violates the girl\'s rights — there are no health benefits','FGM is only harmful if performed by untrained practitioners, so a medical professional should do it instead','FGM is a cultural matter and health workers should not interfere','','B','FGM is illegal under the Prohibition of FGM Act 2011, causes serious health harm with no medical benefits, and violates a girl\'s rights to health, bodily integrity, and freedom from violence. Medicalised FGM is also illegal and condemned by the WHO — it does not reduce the harm.',3,'post','fgm_gbv','MEDIUM'],
        [17,'msq','Rehema is a peer educator in Garissa explaining why FGM violates human rights. Which of the following rights does FGM violate? Select ALL that apply.','The right to health','The right to bodily integrity','The right to freedom from violence and torture','The right to life (when FGM causes death)','The right to practise harmful cultural traditions without legal consequence','A,B,C,D','FGM violates the right to health (causes serious harm), bodily integrity (performed without meaningful consent), freedom from violence, and the right to life when it results in death. Option E is false — harmful cultural practices do not override the law or human rights under the Constitution of Kenya 2010 or the Prohibition of FGM Act 2011.',4,'post','fgm_gbv','MEDIUM'],
        [17,'mcq','Grace, a Form 4 student in Kisumu, is asked: what is the single most important reason why alternative rites of passage are promoted in communities where FGM has been practised? What is the best answer?','They allow communities to abandon all cultural practices entirely','They celebrate girls\' transition to adulthood while preserving cultural identity without causing physical harm','They are cheaper than traditional FGM ceremonies','They are required by the Kenyan government for all communities','','B','Alternative rites of passage are promoted because they allow communities to celebrate a girl\'s transition to womanhood and preserve cultural identity while removing the harmful cutting element. This approach respects culture while protecting girls\' health and rights, making community acceptance more likely.',5,'post','fgm_gbv','MEDIUM'],

        // ---- MODULE 18 — pre ----
        [18,'mcq','What is gambling?','Saving money in a bank account to earn interest','Risking money or valuables on an uncertain outcome hoping to win more','Selling goods at a market stall for profit','Working overtime to earn extra wages','','B','Gambling means staking money or something of value on an event with an uncertain outcome, with the hope of winning more than you put in. It is different from saving or working for money.',1,'pre','gambling','MEDIUM'],
        [18,'mcq','Which of the following is a popular sports betting company operating in Kenya?','M-Pesa','SportPesa','Equity Bank','Safaricom','','B','SportPesa is one of Kenya\'s most well-known sports betting companies. It allows people to bet on football and other sports using their mobile phones.',2,'pre','gambling','MEDIUM'],
        [18,'mcq','What is the legal minimum age for gambling in Kenya?','16 years','21 years','18 years','25 years','','C','According to the Betting, Lotteries and Gaming Act in Kenya, you must be at least 18 years old to legally participate in any form of gambling. Gambling under 18 is illegal.',3,'pre','gambling','MEDIUM'],
        [18,'msq','Which of the following are examples of gambling activities? (Select all that apply)','Placing a bet on a football match using Betika','Buying a lottery ticket','Playing a slot machine at a casino','Depositing money in a savings account to earn fixed interest','Betting on a horse race','A,B,C,E','Gambling involves staking money on uncertain outcomes. Betting on football, buying lottery tickets, slot machines, and horse racing are all forms of gambling. Saving money in a bank for fixed interest is NOT gambling because the outcome is predictable and guaranteed.',4,'pre','gambling','MEDIUM'],
        [18,'mcq','Kamau, a Form 3 student in Nairobi, says gambling is just a fun way to make quick money. What is the most accurate response?','He is right — gambling is a reliable way to earn income','Gambling is only risky for adults, not students','Gambling is designed so that players lose more than they win over time','Gambling is safe as long as you only bet small amounts','','C','Gambling is designed to favour the house or operator. Over time, the odds mean players lose more money than they win. It is not a reliable source of income for anyone, including young people.',5,'pre','gambling','MEDIUM'],

        // ---- MODULE 18 — lesson ----
        [18,'mcq','Which brain chemical is released when a person wins a bet, making gambling feel exciting and addictive?','Insulin','Serotonin','Dopamine','Adrenaline','','C','Dopamine is the brain\'s "reward" chemical. When you win a bet, dopamine is released, creating feelings of pleasure and excitement. Over time, the brain craves this feeling, which is why gambling can become addictive even when a person keeps losing.',1,'lesson','gambling','MEDIUM'],
        [18,'mcq','What is the "house always wins" principle in gambling?','Casino owners are physically stronger than players','All casino buildings are owned by the government','Gambling businesses are mathematically designed so they profit over time, regardless of individual wins','Players who stay at home always win online bets','','C','The "house always wins" means gambling operators set the odds so that, across all bets placed, they always make a profit. A player may win sometimes, but the system is designed so the operator makes money in the long run.',2,'lesson','gambling','MEDIUM'],
        [18,'msq','Which of the following are signs that someone may have a gambling problem? (Select all that apply)','Lying to family members about how much money was spent on betting','Borrowing money frequently to place more bets','Feeling restless or irritable when trying to stop gambling','Gambling always makes you richer and more financially secure','Neglecting school or work responsibilities because of gambling','A,B,C,E','Problem gambling signs include lying about gambling, borrowing money to gamble, feeling unable to stop, neglecting responsibilities, and feeling irritable when not gambling. The idea that gambling always makes you richer is FALSE — this is a harmful myth.',3,'lesson','gambling','MEDIUM'],
        [18,'mcq','Aisha from Mombasa started betting on Odibets to earn school fees money. She now bets every day and feels anxious when she cannot place a bet. This is best described as:','A smart financial strategy','Problem gambling or gambling addiction','A normal hobby that all teenagers enjoy','A good way to practice mathematics','','B','Aisha\'s behaviour — daily betting and anxiety when she cannot gamble — are classic signs of problem gambling or gambling addiction. This is a recognised health condition that requires support and treatment.',4,'lesson','gambling','MEDIUM'],
        [18,'mcq','What is the "variable reward ratio" and how does it make gambling addictive?','It means gamblers always win the same fixed amount each time they bet','It means unpredictable, random wins keep players gambling because the brain cannot predict when the next reward will come','It means gambling companies reward loyal customers with guaranteed winnings','It is a government policy that limits how much people can win','','B','The variable reward ratio means wins are unpredictable and random. This unpredictability is more addictive than predictable rewards because the brain keeps seeking the next win. It is the same principle used in slot machines and sports betting apps like Betika and Mcheza.',5,'lesson','gambling','MEDIUM'],
        [18,'msq','What are the financial consequences of problem gambling? (Select all that apply)','Spending money meant for food, rent, or school fees on gambling','Accumulating debts from borrowing money to gamble','Losing savings that took a long time to build','Guaranteed recovery of all lost money by betting more','Being unable to afford basic necessities due to gambling losses','A,B,C,E','Problem gambling causes serious financial harm: it drains savings, creates debt, takes money meant for essentials, and can lead to poverty. Believing you can recover losses by gambling more — called "chasing losses" — is a dangerous myth and makes the situation worse, not better.',6,'lesson','gambling','MEDIUM'],
        [18,'mcq','Brian, a Form 4 student in Kisumu, hides his phone to bet on SportPesa and lies to his parents about where his pocket money goes. What does this behaviour suggest?','Brian is being responsible by managing his own money','Brian likely has a gambling problem because he is hiding and lying about his betting','Lying about money is a normal teenage behaviour with no risks','Brian is saving money secretly for a school trip','','B','Lying and hiding gambling behaviour are warning signs of problem gambling. People with gambling problems often feel shame and try to conceal their activities from family members. This secrecy can prevent them from getting the help they need.',7,'lesson','gambling','MEDIUM'],
        [18,'msq','Which of the following are psychological or social consequences of problem gambling? (Select all that apply)','Depression and anxiety caused by repeated losses','Damaged relationships with family and friends due to lying or borrowing money','Poor academic performance from spending time gambling instead of studying','Increased self-confidence and improved social status','Feelings of shame, guilt, and hopelessness','A,B,C,E','Problem gambling harms mental health and relationships. It causes depression, anxiety, guilt, and shame. It strains family relationships and friendships, and reduces academic or work performance. The idea that gambling improves self-confidence or social status is a myth promoted by betting companies.',8,'lesson','gambling','MEDIUM'],
        [18,'mcq','Which organisation in Kenya provides free counselling and support for people with gambling addiction, and what is their toll-free helpline number?','Kenya Red Cross — 1199','NACADA — 0800 723 253','Safaricom customer care — 100','Kenya Police — 999','','B','NACADA (National Authority for the Campaign Against Alcohol and Drug Abuse) provides free support for gambling addiction and substance abuse in Kenya. Their toll-free helpline is 0800 723 253, available to anyone who needs help or knows someone who does.',9,'lesson','gambling','MEDIUM'],
        [18,'mcq','Why are mobile betting apps like Betika and Mcheza considered particularly risky for young people in Kenya?','They require users to travel to Nairobi to place bets','They are very expensive to download from the internet','They make gambling easily accessible at any time, increasing the chance of addiction','They only allow betting on international sports, not Kenyan leagues','','C','Mobile betting apps allow young people to gamble anywhere and at any time using a phone. This constant accessibility removes barriers that might otherwise slow gambling, making it much easier to develop a habit or addiction compared to having to visit a physical betting shop.',10,'lesson','gambling','MEDIUM'],

        // ---- MODULE 18 — post ----
        [18,'mcq','Fatuma in Eldoret lost Ksh 5,000 gambling on SportPesa and decides to bet another Ksh 10,000 to try to win back what she lost. This behaviour is called:','Smart investment recovery','Chasing losses — a dangerous gambling behaviour','Responsible risk management','A normal strategy recommended by betting companies','','B','"Chasing losses" means gambling more to try to recover money already lost. This is one of the most dangerous gambling behaviours because it almost always leads to losing even more money and deepening debt.',1,'post','gambling','MEDIUM'],
        [18,'msq','Which of the following are healthy alternatives to gambling for young people in Kenya? (Select all that apply)','Joining a school sports team or a community youth group','Starting a small savings group (chama) with friends to build money together','Learning a skill such as coding, art, or music to earn money','Placing larger bets to win back previous losses faster','Volunteering in your community to build connections and purpose','A,B,C,E','Healthy alternatives to gambling include sports, savings groups, learning skills, and volunteering. These activities build real skills, relationships, and income without financial risk. Placing larger bets to recover losses is "chasing losses" — a harmful behaviour, not a healthy alternative.',2,'post','gambling','MEDIUM'],
        [18,'mcq','A friend tells you they have been secretly betting on Betika every day after school and have spent all their pocket money. What is the best first step you can take to help them?','Tell them to bet on a different platform where the odds are better','Encourage them to talk to a trusted adult or call NACADA on 0800 723 253','Lend them money so they can keep betting and win back their losses','Post about their problem on social media to embarrass them into stopping','','B','The best way to help a friend with a gambling problem is to encourage them to speak to a trusted adult — a parent, teacher, or counsellor — and to let them know about NACADA\'s free helpline (0800 723 253). Lending them money or betting more will make the problem worse.',3,'post','gambling','MEDIUM'],
        [18,'mcq','Why do gambling companies use celebrity endorsements and flashy advertisements on TV and social media in Kenya?','To warn young people about the dangers of gambling','To help the government collect taxes more efficiently','To make gambling appear glamorous and normal so more people are attracted to bet','To provide educational content about financial literacy','','C','Gambling companies use advertising and celebrity endorsements to normalise gambling and make it look exciting and financially rewarding. This marketing targets young people and influences them to gamble. It is important to think critically about what these advertisements do not show — the losses and harm caused by problem gambling.',4,'post','gambling','MEDIUM'],
        [18,'mcq','Which statement BEST describes a responsible attitude towards gambling for young people in Kenya?','Gambling is a reliable way to supplement your income if you study the odds carefully','Young people should avoid all forms of gambling because the legal age is 18 and the risks are high','Gambling is fine as long as you only bet on football matches, not casino games','Mobile betting is safer than physical betting shops so it is acceptable for teenagers','','B','The most responsible attitude is to avoid gambling entirely until you are a legal adult (18+), and even then to understand the serious financial and psychological risks. No form of gambling is reliably safe or profitable, and mobile betting carries the same risks as any other type of gambling.',5,'post','gambling','MEDIUM'],

        // ---- MODULE 19 — pre ----
        [19,'mcq','What does KCSE stand for in the Kenyan education system?','Kenya Certificate of Secondary Education','Kenya Curriculum for Secondary Examinations','Kenya College of Science and Engineering','Kenya Certificate of School Enrolment','','A','KCSE stands for Kenya Certificate of Secondary Education. It is the national examination taken at the end of Form 4 and is a key gateway to post-secondary opportunities including university, TVET, and colleges.',1,'pre','career_decisions','MEDIUM'],
        [19,'mcq','Akinyi is in Form 3 and feels confused about what career to pursue. Who is the BEST school-based person she should consult first?','The school bursar','The school deputy principal','The school guidance counsellor','The school cook','','C','The guidance counsellor is trained to help students explore their interests, strengths, and career options. They provide structured support for career decision-making within the school setting.',2,'pre','career_decisions','MEDIUM'],
        [19,'msq','Which of the following are examples of post-secondary pathways available to Kenyan students after KCSE?','Enrolling in a public university through KUCCPS','Joining a TVET institution to learn a technical trade','Starting a business or self-employment','Repeating Form 1 from the beginning','Attending a teachers training college','A,B,C,E','After KCSE, students can join public universities via KUCCPS, attend TVET institutions, pursue entrepreneurship, or attend professional colleges such as teacher training colleges. Repeating Form 1 is not a post-secondary pathway.',3,'pre','career_decisions','MEDIUM'],
        [19,'mcq','Ochieng scored a C+ in KCSE. Which institution primarily helps him apply for a public university placement in Kenya?','HELB','KUCCPS','KNEC','NHIF','','B','KUCCPS (Kenya Universities and Colleges Central Placement Service) is the body responsible for placing students who qualify for public university education in Kenya. A minimum grade of C+ is generally required.',4,'pre','career_decisions','MEDIUM'],
        [19,'mcq','Which of the following BEST describes a career myth common among Kenyan secondary school students?','Some careers require university education while others require vocational training','Only students who attend university can become successful professionals','Career planning involves knowing your interests and strengths','TVET institutions offer recognised qualifications in Kenya','','B','The belief that only university graduates can succeed is a career myth. Many successful Kenyan professionals, entrepreneurs, and tradespeople have built thriving careers through TVET, self-employment, or other pathways without a university degree.',5,'pre','career_decisions','MEDIUM'],

        // ---- MODULE 19 — lesson ----
        [19,'mcq','In the career planning process, what should a student do FIRST before exploring career options?','Apply to a university','Conduct a self-assessment of values, interests, skills, and personality','Ask friends which career pays the most','Look at job advertisements in newspapers','','B','The first step in career planning is self-assessment — understanding your values, interests, skills, and personality (VISAP). This foundation helps you identify careers that are a good personal fit before exploring specific options.',1,'lesson','career_decisions','MEDIUM'],
        [19,'msq','The VISAP model for career self-assessment covers which of the following elements?','Values — what matters most to you','Interests — activities you enjoy and find engaging','Skills — things you are good at doing','Appearance — how attractive you look to employers','Personality — your natural traits and working style','A,B,C,E','VISAP stands for Values, Interests, Skills, and Personality. These four elements help a student understand themselves before making career decisions. Appearance is not part of the VISAP model and is not a valid career planning tool.',2,'lesson','career_decisions','MEDIUM'],
        [19,'mcq','Wanjiku wants to become a nurse. She arranges to spend a week at Kenyatta National Hospital observing nurses at work. This activity is called:','An internship contract','A job shadowing experience','An informational interview','A clinical attachment report','','B','Job shadowing involves observing a professional at work over a period of time to gain firsthand understanding of what a career looks like day-to-day. It is different from an internship (which involves doing tasks) or an informational interview (which is a conversation).',3,'lesson','career_decisions','MEDIUM'],
        [19,'mcq','TVET institutions in Kenya offer programmes that are BEST suited for students who want to:','Study medicine at postgraduate level','Gain practical technical and vocational skills for the job market','Qualify for a Master\'s degree without a first degree','Avoid all forms of examinations','','B','TVET (Technical and Vocational Education and Training) institutions focus on equipping students with hands-on technical and vocational skills. Graduates are well-prepared for trades such as plumbing, electrical work, ICT, automotive engineering, and many others.',4,'lesson','career_decisions','MEDIUM'],
        [19,'msq','Which of the following are among Kenya\'s identified fast-growing economic sectors that offer career opportunities for young people?','Information and Communications Technology (ICT)','Agriculture and agribusiness','Healthcare and medical services','Travelling to Mars for mining operations','Tourism and hospitality','A,B,C,E','Kenya\'s growing sectors include ICT, agriculture, healthcare, tourism and hospitality, and construction, among others. These sectors offer real and expanding career opportunities for young Kenyans. Space mining is not a current career opportunity available to Kenyan students.',5,'lesson','career_decisions','MEDIUM'],
        [19,'mcq','Kamau wants to attend a public university but his family cannot afford the fees. Which Kenyan government body can provide him with a student loan?','Kenya Revenue Authority (KRA)','Higher Education Loans Board (HELB)','National Social Security Fund (NSSF)','Kenya National Examinations Council (KNEC)','','B','HELB (Higher Education Loans Board) provides loans and scholarships to Kenyan students pursuing higher education. Students can apply for HELB loans to cover tuition and upkeep costs at public universities and approved institutions.',6,'lesson','career_decisions','MEDIUM'],
        [19,'mcq','An informational interview is BEST described as:','A formal job interview for employment','A conversation with a working professional to learn about their career','An examination to test your career knowledge','A government form for KUCCPS application','','B','An informational interview is an informal conversation with someone working in a field you are interested in. The goal is to gather information about the career, not to apply for a job. It is a valuable tool for career exploration.',7,'lesson','career_decisions','MEDIUM'],
        [19,'msq','Which of the following are recommended steps in a structured career planning process?','Conduct a self-assessment to understand your strengths and interests','Explore different career options and the qualifications required','Decide on a career direction based on your research and self-knowledge','Pick the career your neighbour chose without thinking about your own interests','Create an action plan with goals and steps to reach your career target','A,B,C,E','Career planning involves: self-assess → explore → decide → plan → act. These five steps help ensure your career choice is informed and personally meaningful. Blindly copying someone else\'s choice without self-reflection is not a recommended step.',8,'lesson','career_decisions','MEDIUM'],
        [19,'mcq','Fatuma\'s parents want her to become a doctor, but she is passionate about graphic design and technology. According to career planning principles, whose interests should PRIMARILY guide her career decision?','Her parents\' interests, because they have more life experience','Her teachers\' recommendations, because they know her grades','Her own interests, values, and skills','Her classmates\' opinions, because they know her personality','','C','While advice from parents and teachers is valuable, career decisions should be primarily guided by the individual\'s own values, interests, skills, and personality. A career that aligns with personal strengths and passions leads to greater satisfaction and long-term success.',9,'lesson','career_decisions','MEDIUM'],
        [19,'mcq','Which of the following statements about private universities in Kenya is TRUE?','Private universities in Kenya are not recognised by the government','Private universities in Kenya charge no fees at all','Private universities in Kenya are accredited and offer recognised degree programmes','Private universities only admit students who failed KCSE','','C','Private universities in Kenya, such as Strathmore University, United States International University (USIU), and others, are accredited by the Commission for University Education (CUE) and offer recognised degree programmes. They do have tuition fees and have their own admission requirements.',10,'lesson','career_decisions','MEDIUM'],

        // ---- MODULE 19 — post ----
        [19,'msq','Which of the following are TRUE statements about TVET education in Kenya?','TVET institutions offer certificates, diplomas, and artisan qualifications','TVET graduates can work in sectors such as construction, ICT, and hospitality','TVET is a recognised and valued pathway that does not require a university degree','TVET qualifications are not accepted by any employer in Kenya','Students who score below C+ in KCSE can still access TVET programmes','A,B,C,E','TVET institutions in Kenya provide valuable qualifications at certificate and diploma levels across many sectors. They are accessible to students with various KCSE grades and their graduates are employable in multiple industries. The claim that no employer accepts TVET qualifications is false.',1,'post','career_decisions','MEDIUM'],
        [19,'mcq','Otieno scored a B plain in KCSE and is considering his options. Which organisation should he contact to apply for placement in a public university in Kenya?','Kenya National Examinations Council (KNEC)','Kenya Universities and Colleges Central Placement Service (KUCCPS)','Kenya Revenue Authority (KRA)','National Employment Authority (NEA)','','B','KUCCPS manages placement of qualifying students into public universities and colleges in Kenya. Students with a minimum of C+ (and above for competitive programmes) apply through the KUCCPS portal using their KCSE index number.',2,'post','career_decisions','MEDIUM'],
        [19,'mcq','Which of the following is the MOST accurate description of how values relate to career decision-making?','Values have no connection to career choices','Values help you identify careers that align with what matters most to you personally','Values only matter after you have already chosen a career','Values are only important for religious careers','','B','Your values — such as helping others, financial security, creativity, or independence — are a core part of self-assessment. Choosing a career that aligns with your values increases motivation, job satisfaction, and a sense of purpose throughout your working life.',3,'post','career_decisions','MEDIUM'],
        [19,'mcq','Nyambura completed Form 4 and is unsure about her career path. She visits her school\'s guidance office for help. What is the PRIMARY role of the guidance counsellor in this situation?','To choose a career for Nyambura and submit her application','To discourage her from pursuing university education','To help Nyambura explore her interests, strengths, and available options','To grade her KCSE results and recommend a university course','','C','The guidance counsellor\'s primary role is to support students in self-discovery and career exploration — not to make decisions for them. They help students understand themselves and the options available so that students can make informed choices.',4,'post','career_decisions','MEDIUM'],
        [19,'msq','Which of the following actions would BEST help a Form 4 student in Kenya make a well-informed career decision?','Conducting a self-assessment using a tool like VISAP to understand personal strengths','Speaking with a guidance counsellor about available career pathways','Doing job shadowing or informational interviews with professionals in fields of interest','Choosing a career solely because it is the most popular choice among classmates','Researching Kenya\'s growing economic sectors and the qualifications they require','A,B,C,E','Informed career decision-making involves self-assessment, professional guidance, direct exposure to careers through shadowing or informational interviews, and research into the job market. Copying classmates\' choices without personal reflection is not a sound strategy.',5,'post','career_decisions','MEDIUM'],

        // ---- MODULE 20 — pre ----
        [20,'mcq','Which Kenyan law was enacted in 2018 to specifically address cyber crimes?','The Kenya Information and Communications Act','The Data Protection Act','The Computer Misuse and Cybercrimes Act','The National Cohesion and Integration Act','','C','The Computer Misuse and Cybercrimes Act (CMCA) was passed in Kenya in 2018. It criminalises offences such as hacking, cyber fraud, cyberbullying, and the sharing of intimate images without consent.',1,'pre','cyber_crimes','MEDIUM'],
        [20,'mcq','Akinyi receives an SMS claiming to be from Safaricom asking her to click a link and enter her M-Pesa PIN to avoid account suspension. This is an example of:','Cyberbullying','Identity theft','Phishing','Hacking','','C','Phishing is a scam where criminals pretend to be trusted organisations (like Safaricom or banks) to trick you into giving up personal information such as PINs, passwords, or account numbers.',2,'pre','cyber_crimes','MEDIUM'],
        [20,'mcq','Which of the following is the correct email address for reporting cyber crimes to Kenya\'s Directorate of Criminal Investigations (DCI)?','cybercrime@nps.go.ke','report@ca.go.ke','cybercrime@dci.go.ke','helpdesk@safaricom.co.ke','','C','Cyber crimes in Kenya can be reported to the DCI at cybercrime@dci.go.ke. You can also call the Communications Authority on the toll-free line 0800 721 577 or contact Childline Kenya on 116.',3,'pre','cyber_crimes','MEDIUM'],
        [20,'mcq','Sextortion occurs when someone threatens to share your intimate images or videos unless you:','Report them to the police','Block them on social media','Pay them money or send more intimate content','Change your password immediately','','C','Sextortion is a form of blackmail where a person threatens to share intimate images or videos of you unless you pay money or comply with other demands. It is a crime under Kenya\'s Computer Misuse and Cybercrimes Act.',4,'pre','cyber_crimes','MEDIUM'],
        [20,'msq','Which of the following are examples of cyberbullying? (Select all that apply)','Sending repeated threatening messages to a classmate on WhatsApp','Creating a fake profile to mock a student from your school','Sharing embarrassing photos of someone without their permission','Sending a friend a birthday greeting on Instagram','Posting hurtful rumours about someone online to make others laugh','A,B,C,E','Cyberbullying involves using digital platforms to harass, threaten, humiliate, or harm others. Sending birthday greetings is positive and not cyberbullying. All other options describe harmful online behaviour that can have serious emotional consequences.',5,'pre','cyber_crimes','MEDIUM'],

        // ---- MODULE 20 — lesson ----
        [20,'mcq','Under the Computer Misuse and Cybercrimes Act 2018, what is the maximum prison sentence for unauthorised access to a computer system (hacking)?','1 year','3 years','5 years','10 years','','B','The CMCA 2018 prescribes a fine of up to KSh 5 million or imprisonment of up to 3 years, or both, for the offence of unauthorised access to a computer system. More serious offences carry heavier penalties.',1,'lesson','cyber_crimes','MEDIUM'],
        [20,'mcq','Omondi from Eldoret notices that a website asking for his school login details has the URL "http://school-portal-kenya.xyz" instead of the official school website. The best action is to:','Enter his details quickly and close the tab','Share the link with friends to warn them','Close the page immediately and report it to a trusted adult or the school IT team','Reply to the page asking if it is legitimate','','C','Fake websites (a form of phishing) often use slightly different URLs to trick users. Always check the official URL carefully. If in doubt, close the page, do not enter any details, and report it to a trusted adult or relevant authority.',2,'lesson','cyber_crimes','MEDIUM'],
        [20,'msq','Which of the following steps help protect your M-Pesa and online accounts from cyber criminals? (Select all that apply)','Using a strong password that combines letters, numbers, and symbols','Enabling two-factor authentication (2FA) on your accounts','Sharing your PIN only with close friends you trust','Never clicking on links in unsolicited SMS or email messages','Regularly updating your passwords and not reusing them across accounts','A,B,D,E','Strong passwords, 2FA, avoiding suspicious links, and changing passwords regularly are all key protections. You should NEVER share your PIN with anyone — not even close friends — because this is how many M-Pesa frauds happen.',3,'lesson','cyber_crimes','MEDIUM'],
        [20,'mcq','Fatuma, a Form 3 student in Mombasa, receives a nude photo from an unknown number on WhatsApp. What should she do?','Forward it to her friends so they know about the sender','Keep it private and ignore it','Do not open or forward it; report it to a trusted adult and block the sender','Reply to ask why they sent it','','C','Receiving unsolicited sexual content is a crime under the CMCA 2018. The correct response is to NOT open, save, or forward the image, report to a trusted adult or the DCI, and block the sender immediately.',4,'lesson','cyber_crimes','MEDIUM'],
        [20,'mcq','Identity theft online means:','Losing your national ID card at a shopping mall','Someone pretending to be you online using your personal information to commit fraud','Forgetting your social media password','Blocking someone from using your device','','B','Online identity theft involves someone stealing your personal information — such as your name, ID number, or account credentials — and using it to impersonate you, access your accounts, or commit fraud in your name.',5,'lesson','cyber_crimes','MEDIUM'],
        [20,'msq','Wanjiku is being blackmailed: someone has an intimate photo of her and is demanding money. Which of the following should she do? (Select all that apply)','Do not pay the blackmailer — paying rarely stops the demands','Report the matter to the DCI at cybercrime@dci.go.ke','Tell a trusted adult such as a parent, teacher, or counsellor','Immediately delete all her social media accounts permanently','Contact Childline Kenya on 116 for support and guidance','A,B,C,E','If you are being sextorted, do not pay — it encourages more demands. Report to the DCI, tell a trusted adult, and call Childline 116. Deleting all your accounts is not necessary and could destroy evidence needed for prosecution.',6,'lesson','cyber_crimes','MEDIUM'],
        [20,'mcq','Which government body in Kenya is responsible for regulating the communications sector and can receive complaints about online harmful content?','The Kenya Revenue Authority (KRA)','The Communications Authority of Kenya (CA)','The Ethics and Anti-Corruption Commission (EACC)','The National Transport and Safety Authority (NTSA)','','B','The Communications Authority of Kenya regulates the ICT sector and handles complaints about harmful online content. Its toll-free helpline is 0800 721 577. For criminal cyber offences, contact the DCI.',7,'lesson','cyber_crimes','MEDIUM'],
        [20,'mcq','Brian from Nairobi uses his neighbour\'s Wi-Fi without permission and accesses their personal files stored on a shared folder. Under the CMCA 2018, Brian has committed:','A minor infringement with no legal consequences','Unauthorised access to a computer system, which is a criminal offence','A civil matter that can only be resolved in a civil court','Nothing wrong because he did not steal any money','','B','Accessing any computer system, network, or data without authorisation is a criminal offence under Section 3 of Kenya\'s Computer Misuse and Cybercrimes Act 2018, regardless of whether money was stolen.',8,'lesson','cyber_crimes','MEDIUM'],
        [20,'msq','Which of the following are signs that an online message may be a phishing attempt? (Select all that apply)','The message creates urgency, e.g. "Your account will be closed in 24 hours"','The sender\'s email address looks slightly wrong, e.g. safar1com@mail.com','The message asks you to click a link and enter your PIN or password','The message is a reply to an email you sent yesterday','The link in the message leads to a website that looks slightly different from the official one','A,B,C,E','Phishing messages typically create false urgency, use spoofed sender addresses, direct you to fake websites, and ask for sensitive information. A genuine reply to your own sent email is less likely to be phishing; the other four options are classic warning signs.',9,'lesson','cyber_crimes','MEDIUM'],
        [20,'mcq','Privacy settings on social media platforms are important because they:','Allow you to follow more people automatically','Let you control who can see your personal information and posts','Increase the speed of your internet connection','Automatically delete old posts after 30 days','','B','Privacy settings give you control over who can view your profile, photos, location, and other personal data. Keeping your accounts private reduces the risk of strangers accessing your information for harmful purposes.',10,'lesson','cyber_crimes','MEDIUM'],

        // ---- MODULE 20 — post ----
        [20,'mcq','Amina receives a Facebook friend request from someone she does not know who immediately starts asking personal questions including where she goes to school and her home location in Kisumu. The safest response is to:','Answer the questions because the person seems friendly','Accept the request but answer only some questions','Decline the request and block the account; report if the person persists','Ask the person to video call to verify their identity','','C','Strangers asking for your location and school details online is a red flag. Predators use social media to identify and groom young people. Decline, block, and report such accounts to the platform and a trusted adult.',1,'post','cyber_crimes','MEDIUM'],
        [20,'mcq','Which of the following is the Childline Kenya toll-free number that young people can call for help with online safety issues, including sextortion or cyberbullying?','999','116','0800 721 577','0700 000 000','','B','Childline Kenya\'s toll-free number is 116. It is available 24/7 and offers confidential support to children and young people facing abuse, including online abuse such as sextortion and cyberbullying.',2,'post','cyber_crimes','MEDIUM'],
        [20,'msq','Which of the following describe responsible digital behaviour for secondary school students in Kenya? (Select all that apply)','Thinking before you post — once online, content is hard to take back','Respecting others\' privacy by not sharing their photos or information without consent','Using strong, unique passwords and enabling 2FA on all important accounts','Sharing your school timetable and home address publicly on social media','Reporting harmful or illegal content to platform moderators or the DCI','A,B,C,E','Responsible digital behaviour includes thinking before posting, respecting privacy, using strong passwords, and reporting harmful content. Publicly sharing your timetable and home address is dangerous as it can expose you to physical and online threats.',3,'post','cyber_crimes','MEDIUM'],
        [20,'mcq','Peter notices that his friend Kamau has been posting very hurtful comments about another student, Grace, on TikTok and encouraging others to mock her. Peter should:','Join in because Kamau is his friend','Stay silent to avoid conflict','Tell Kamau to stop, support Grace, and report the posts to the platform and a trusted adult if it continues','Screenshot the posts and share them further so more people see what Kamau did','','C','Cyberbullying harms victims deeply. Bystanders have a responsibility to speak up. The right actions are to tell the bully to stop, support the victim, and report the behaviour to the platform and a trusted adult or school authority.',4,'post','cyber_crimes','MEDIUM'],
        [20,'mcq','Under Kenya\'s Computer Misuse and Cybercrimes Act 2018, sharing an intimate image of another person online without their consent is:','Only wrong if the victim complains formally','A criminal offence that can result in a fine or imprisonment','Allowed if the image was originally sent to you willingly','Not covered by any Kenyan law','','B','Section 27 of the CMCA 2018 criminalises the publication of false, misleading, or intimate images without consent. Sharing intimate images without the subject\'s consent — even if they were originally shared privately — is a criminal offence punishable by a fine of up to KSh 5 million or up to 2 years in prison, or both.',5,'post','cyber_crimes','MEDIUM'],

        // ---- MODULE 21 — pre ----
        [21,'mcq','According to Genesis 1:27, God created human beings as:','Spiritual beings with no physical form','Male and female, in His own image','Animals with higher intelligence','Independent beings free from any design','','B','Genesis 1:27 states: "So God created mankind in his own image, in the image of God he created them; male and female he created them." Sexuality is part of God\'s intentional creation.',1,'pre','biblical_sexuality','MEDIUM'],
        [21,'mcq','Wanjiku asks her church youth leader what the Bible says about sex before marriage. The most accurate Biblical answer is:','The Bible does not address sex before marriage directly','Sex before marriage is a personal decision with no spiritual consequences','The Bible calls believers to abstain from sexual immorality and honour God with their bodies','Sexual purity is only important for girls, not boys','','C','1 Thessalonians 4:3-4 teaches: "It is God\'s will that you should be sanctified: that you should avoid sexual immorality; that each of you should learn to control your own body in a way that is holy and honourable." This applies equally to all.',2,'pre','biblical_sexuality','MEDIUM'],
        [21,'mcq','Genesis 2:24 says "a man shall leave his father and mother and be united to his wife." This verse establishes that:','Marriage is an optional social custom','Sexual union is designed by God for the covenant of marriage','A man may have multiple wives equally honoured by God','Physical intimacy should be avoided even in marriage','','B','Genesis 2:24 is the foundation of God\'s design: one man, one woman, united in marriage — a covenant before God. Jesus himself quoted this verse in Matthew 19:4-5 to reaffirm this design.',3,'pre','biblical_sexuality','MEDIUM'],
        [21,'mcq','Hassan has been watching pornography and finds it hard to stop. Which verse best speaks to this struggle?','John 3:16 — God so loved the world','Matthew 5:28 — looking with lust is committing adultery in the heart','Psalm 23:1 — the Lord is my shepherd','Romans 8:1 — no condemnation for those in Christ','','B','Jesus said in Matthew 5:28: "Anyone who looks at a woman lustfully has already committed adultery with her in his heart." Pornography feeds lust and violates the standard of sexual purity God calls us to.',4,'pre','biblical_sexuality','MEDIUM'],
        [21,'mcq','Which Old Testament figure is most celebrated as a Biblical example of sexual integrity when he fled from temptation?','King Solomon','Samson','Joseph','David','','C','Joseph (Genesis 39) refused to sleep with Potiphar\'s wife and literally fled the scene. His response — "How then could I do such a wicked thing and sin against God?" — is a model of sexual integrity under pressure.',5,'pre','biblical_sexuality','MEDIUM'],

        // ---- MODULE 21 — lesson ----
        [21,'mcq','Kamau is a Form 3 student who has made mistakes in the past and wonders if God can forgive him and give him a fresh start sexually. Which Scripture offers him the clearest hope?','Proverbs 6:32 — adultery destroys a man','1 John 1:9 — if we confess our sins, He is faithful to forgive and purify us','Numbers 5:11 — the law of jealousy','Leviticus 18:20 — do not have sexual relations with a neighbour\'s wife','','B','1 John 1:9 promises: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness." No past failure is beyond God\'s restoration.',1,'lesson','biblical_sexuality','MEDIUM'],
        [21,'mcq','The concept of "secondary virginity" means:','Undergoing a medical procedure to restore virginity','Making a fresh commitment to abstinence after previously being sexually active','A virginity test conducted by a church elder','Denying that one has ever been sexually active','','B','Secondary virginity is a sincere recommitment to sexual purity before God, regardless of past experiences. It is grounded in God\'s ability to restore and renew (2 Corinthians 5:17 — "new creation").',2,'lesson','biblical_sexuality','MEDIUM'],
        [21,'mcq','Akinyi notices that her boyfriend constantly pressures her to have sex and dismisses her discomfort. From a Biblical perspective, this relationship is:','Normal — boys naturally have stronger desires','Honouring, because he is committed to her','Problematic — a God-honouring relationship is built on respect and mutual honour, not pressure','Fine as long as they plan to marry eventually','','C','Philippians 2:3-4 calls believers to "value others above yourselves." A partner who pressures and dismisses boundaries is not loving as Christ loves — they are seeking self-gratification, not the other\'s wellbeing.',3,'lesson','biblical_sexuality','MEDIUM'],
        [21,'msq','Brian is a youth leader preparing a talk on practical ways to maintain sexual purity. Which of the following are Biblical and practical strategies he should include?','Avoiding situations and media that fuel lust (flee youthful lusts — 2 Timothy 2:22)','Staying accountable to a trusted Christian friend or mentor','Viewing pornography occasionally as a safe outlet for sexual desire','Renewing your mind daily through Scripture and prayer (Romans 12:2)','Setting clear physical boundaries in relationships before temptation arises','A,B,D,E','2 Timothy 2:22 says "flee the evil desires of youth." Romans 12:2 calls for mind renewal. Accountability and pre-commitment boundaries are proven strategies. Pornography is never a safe outlet — it fuels lust and damages the mind (Matthew 5:28).',4,'lesson','biblical_sexuality','MEDIUM'],
        [21,'mcq','In the story of Ruth and Boaz (Book of Ruth), their relationship is held up as a Biblical example because:','They lived together before marriage to test compatibility','Boaz pursued Ruth secretly without her knowledge','Their relationship was marked by honour, integrity, and adherence to God\'s covenant customs','Ruth seduced Boaz to secure financial security','','C','Ruth and Boaz\'s relationship models honourable courtship: Boaz protected Ruth\'s dignity, followed proper redemption customs, and acted with integrity. It is a picture of a God-honouring relationship built on character, not manipulation.',5,'lesson','biblical_sexuality','MEDIUM'],
        [21,'mcq','Fatuma learns that a classmate contracted an STI after engaging in sex outside marriage. From a Biblical-health perspective, this illustrates:','That God punishes people who sin sexually with illness','That sexual activity outside God\'s design carries real physical, emotional, and spiritual risks','That STIs only affect people with weak faith','That the classmate needed better contraception, not abstinence','','B','The Bible does not teach that every illness is divine punishment, but it does teach that sexual immorality carries inherent risks (Proverbs 6:27-28). STIs, unplanned pregnancies, and emotional wounds are real consequences of sex outside the protective covenant of marriage.',6,'lesson','biblical_sexuality','MEDIUM'],
        [21,'mcq','Psalm 51 records David\'s prayer after his sin with Bathsheba. The primary lesson for young people from this Psalm is:','Powerful people can do whatever they want and be forgiven','Sin has no lasting consequences if you are a person of faith','Genuine repentance — acknowledging sin, taking responsibility, and seeking God\'s cleansing — leads to restoration','David\'s prayer shows that sexual sin is worse than other sins','','C','Psalm 51 is the model prayer of repentance: "Create in me a pure heart, O God." David acknowledged his sin fully, took personal responsibility, and trusted in God\'s steadfast love. Restoration came through genuine repentance, not self-justification.',7,'lesson','biblical_sexuality','MEDIUM'],
        [21,'msq','Otieno is writing a church newsletter article on what the Bible says about sexual purity. Which of the following statements are Biblically accurate and should be included?','Sexual purity includes the mind and emotions, not just physical actions','God designed sexual intimacy as a gift to be enjoyed within the covenant of marriage','Sexual sin is unforgivable and permanently disqualifies a person from God\'s purposes','The Holy Spirit helps believers to exercise self-control over sexual desires (Galatians 5:22-23)','Young people can make a meaningful commitment to purity at any age','A,B,D,E','Purity is holistic — thoughts, emotions, and body (Matthew 5:28, 1 Thessalonians 4:3-5). God designed sex as a gift within marriage (Genesis 2:24). The Spirit produces self-control (Galatians 5:22-23). No sin is unforgivable (1 John 1:9). Commitment to purity is open to all at any stage.',8,'lesson','biblical_sexuality','MEDIUM'],
        [21,'mcq','Miriam is 17 and has decided to take a purity pledge at her church. A friend mocks her saying "keeping your virginity is old-fashioned and has no real benefits." The BEST Biblical and practical response Miriam can give is:','Agree that it is old-fashioned but keep the pledge anyway to please her parents','Sexual purity protects from STIs and unplanned pregnancy, and honours God\'s design for human flourishing — it is wisdom, not weakness','Tell her friend that she will go to hell for asking such a question','Abandon the pledge to fit in socially','','B','1 Corinthians 6:19-20 teaches that our bodies are temples of the Holy Spirit and we are to honour God with our bodies. Abstinence has both spiritual and documented health benefits. Purity is counter-cultural courage, not weakness.',9,'lesson','biblical_sexuality','MEDIUM'],
        [21,'mcq','According to 1 Corinthians 6:19-20, the reason believers are called to honour God with their bodies is:','Because God dislikes pleasure and wants people to suffer','Because your body is the temple of the Holy Spirit and you were bought at a price','Because physical appearance determines spiritual worth','Because sex is inherently sinful and shameful','','B','Paul writes: "Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own; you were bought at a price. Therefore honour God with your bodies." Our bodies belong to God and deserve dignified care.',10,'lesson','biblical_sexuality','MEDIUM'],

        // ---- MODULE 21 — post ----
        [21,'mcq','After completing this module, Kamau summarises the key message to a friend. Which summary is MOST accurate?','God created sexuality, and the Bible gives us wisdom to honour Him with our bodies through purity, healthy relationships, and restoration when we fail','The Bible teaches that all sexual feelings are sinful and must be suppressed completely','Sexuality is a private matter and the Bible is mostly silent on the topic','Only people who have never been sexually active can be used by God','','A','The module\'s core message: God is the author of sexuality (Genesis 1-2), calls us to purity (1 Thessalonians 4:3), and offers full restoration when we fail (1 John 1:9, Psalm 51). Healthy, honourable relationships are possible and encouraged.',1,'post','biblical_sexuality','MEDIUM'],
        [21,'mcq','Akinyi\'s younger sister asks why Joseph ran away from Potiphar\'s wife instead of simply saying no. The best answer is:','Joseph was afraid of being beaten','Joseph ran because fleeing temptation is sometimes wiser than standing to argue — he prioritised obedience to God over social embarrassment','Joseph did not find her attractive','The Bible does not explain Joseph\'s motives','','B','Genesis 39:12 says Joseph "ran out of the house." 2 Timothy 2:22 echoes this principle: "Flee the evil desires of youth." Sometimes the wisest response to sexual temptation is rapid physical and mental distance, not debate.',2,'post','biblical_sexuality','MEDIUM'],
        [21,'msq','Hassan has a friend who says "I have sinned so many times sexually — God cannot want anything to do with me anymore." Which of the following are true and helpful Biblical responses Hassan can share?','1 John 1:9 promises forgiveness and purification to all who sincerely confess','Psalm 51 shows that even David, a man after God\'s own heart, was restored after sexual sin','Some sexual sins are permanent and place a person beyond God\'s grace','2 Corinthians 5:17 teaches that in Christ, a person becomes a new creation — the old has gone','God\'s love is not based on our sexual history but on His character (Romans 8:38-39)','A,B,D,E','No sexual sin places a person beyond God\'s grace. 1 John 1:9 and Psalm 51 confirm forgiveness is available. 2 Corinthians 5:17 speaks of new creation. Romans 8:38-39 affirms nothing can separate us from God\'s love. Option C is false — it contradicts the gospel.',3,'post','biblical_sexuality','MEDIUM'],
        [21,'mcq','Wanjiku is in a relationship and wants it to honour God. Which action BEST reflects the principles taught in this module?','Agreeing to have sex once to show her boyfriend she trusts him','Hiding the relationship from family to avoid accountability','Setting physical boundaries early, staying accountable to a mentor, and regularly evaluating whether the relationship builds both of them up in faith','Avoiding all romantic feelings because they are inherently sinful','','C','A God-honouring relationship is intentional about purity. Setting boundaries, maintaining accountability, and asking whether the relationship builds Christlike character are practical applications of 1 Thessalonians 4:3-4 and Philippians 4:8.',4,'post','biblical_sexuality','MEDIUM'],
        [21,'mcq','Otieno argues that pornography is harmless because "you are not actually touching anyone." From this module, the best counter-argument is:','Pornography is only harmful if you watch it alone','Jesus taught in Matthew 5:28 that lust in the heart is sin; pornography deliberately cultivates lust, damages how you view people, and can lead to addiction','Pornography is harmful only for younger teenagers, not for those over 18','The Bible does not specifically mention pornography so it cannot be judged','','B','Matthew 5:28 shows that lust — the deliberate cultivation of sexual desire for someone outside marriage — is sin regardless of physical contact. Pornography fuels lust, objectifies human beings made in God\'s image, and creates neurological addiction patterns. It violates sexual purity at the level of the heart.',5,'post','biblical_sexuality','MEDIUM'],
    ];

    // Group by module_id and section so we can do count-check per group
    $byModuleSection = [];
    foreach ($allQuestions as $q) {
        $key = $q[0] . '|' . $q[11]; // module_id|section
        $byModuleSection[$key][] = $q;
    }

    $totalInserted = 0;
    foreach ($byModuleSection as $key => $questions) {
        [$mid, $section] = explode('|', $key);
        $mid = (int)$mid;
        $count = (int)$db->querySingle("SELECT COUNT(*) FROM quiz_questions WHERE module_id=$mid AND section='" . $db->escapeString($section) . "'");
        if ($count == 0) {
            $inserted = 0;
            foreach ($questions as $q) {
                $db->exec("INSERT INTO quiz_questions
                    (module_id, question_type, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, sort_order, is_published, section, competency, difficulty)
                    VALUES (
                        " . (int)$q[0] . ",
                        '" . $db->escapeString($q[1]) . "',
                        '" . $db->escapeString($q[2]) . "',
                        '" . $db->escapeString($q[3]) . "',
                        '" . $db->escapeString($q[4]) . "',
                        '" . $db->escapeString($q[5]) . "',
                        '" . $db->escapeString($q[6]) . "',
                        '" . $db->escapeString($q[7]) . "',
                        '" . $db->escapeString($q[8]) . "',
                        '" . $db->escapeString($q[9]) . "',
                        '" . $db->escapeString($q[10]) . "',
                        1,
                        '" . $db->escapeString($q[11]) . "',
                        '" . $db->escapeString($q[12]) . "',
                        '" . $db->escapeString($q[13]) . "'
                    );");
                $inserted++;
            }
            $totalInserted += $inserted;
            $results[] = ok("Step 7: Inserted $inserted questions for module $mid / section '$section'");
        } else {
            $results[] = ok("Step 7: Skipped module $mid / section '$section' — already has $count questions");
        }
    }
    $results[] = ok("Step 7: Total new questions inserted this run: $totalInserted");

    $db->close();

} catch (Exception $e) {
    $errors[] = fail('EXCEPTION: ' . $e->getMessage());
}

// -------------------------------------------------------------------------
// OUTPUT
// -------------------------------------------------------------------------
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ARISE Migration — 2026-05-11</title>
<style>
  body { font-family: monospace; background: #f4f4f4; padding: 2em; }
  h1 { color: #333; }
  ul { list-style: none; padding: 0; }
  li { padding: 4px 0; font-size: 0.95em; }
  .box { background: #fff; border: 1px solid #ddd; padding: 1.5em; border-radius: 6px; max-width: 900px; }
  .err { background: #fff0f0; border-color: #f99; padding: 1em; margin-top: 1em; border-radius: 4px; }
</style>
</head>
<body>
<div class="box">
<h1>ARISE Migration — 2026-05-11</h1>
<p>DB path: <?= htmlspecialchars($dbPath) ?></p>
<ul>
<?php foreach ($results as $r) echo $r . "\n"; ?>
</ul>
<?php if (!empty($errors)): ?>
<div class="err">
<strong>Errors:</strong>
<ul><?php foreach ($errors as $e) echo $e . "\n"; ?></ul>
</div>
<?php endif; ?>
<p style="margin-top:1.5em;color:#888;font-size:0.85em">Script self-deleted after execution.</p>
</div>
</body>
</html>
<?php
// Self-delete
@unlink(__FILE__);
