<?php
// Migration: refusal skills lessons + module 17 quiz questions
$db = new SQLite3('/home/cpmsfdav/public_html/arise/data/arise.db');
$db->exec('PRAGMA journal_mode=WAL;');
$steps = [];

// Step 1: Insert 8 refusal skills lesson records
$existing = $db->querySingle("SELECT COUNT(*) FROM lessons WHERE slug LIKE 'refusal-skills-%'");
if ($existing < 8) {
    $sql = "INSERT OR IGNORE INTO lessons (module_id, title, slug, lesson_type, file_path, sort_order, is_active, is_published) VALUES
    (1, 'Refusal Skills – Drugs & Substance Abuse', 'refusal-skills-drugs', 'interactive', 'interactive/lesson-refusal-drugs.html', 99, 1, 1),
    (2, 'Refusal Skills – Healthy Relationships', 'refusal-skills-relationships', 'interactive', 'interactive/lesson-refusal-relationships.html', 99, 1, 1),
    (3, 'Refusal Skills – Abstinence', 'refusal-skills-abstinence', 'interactive', 'interactive/lesson-refusal-abstinence.html', 99, 1, 1),
    (4, 'Refusal Skills – GBV', 'refusal-skills-gbv', 'interactive', 'interactive/lesson-refusal-gbv.html', 99, 1, 1),
    (5, 'Refusal Skills – HIV/AIDS & STIs', 'refusal-skills-hiv', 'interactive', 'interactive/lesson-refusal-hiv.html', 99, 1, 1),
    (9, 'Refusal Skills – Social Media & SRH', 'refusal-skills-social-media', 'interactive', 'interactive/lesson-refusal-social-media.html', 99, 1, 1),
    (18, 'Refusal Skills – Gambling', 'refusal-skills-gambling', 'interactive', 'interactive/lesson-refusal-gambling.html', 99, 1, 1),
    (20, 'Refusal Skills – Cyber Crimes', 'refusal-skills-cyber', 'interactive', 'interactive/lesson-refusal-cyber.html', 99, 1, 1);";
    $db->exec($sql);
    $steps[] = "Step 1: Inserted refusal skills lessons ✓";
} else {
    $steps[] = "Step 1: Refusal skills lessons already exist (skipped)";
}

// Step 2: Insert module 17 (FGM/GBV) quiz questions
$existing17 = $db->querySingle("SELECT COUNT(*) FROM quiz_questions WHERE module_id=17 AND competency='fgm_gbv'");
if ($existing17 < 20) {
    $sql = "INSERT INTO quiz_questions (module_id, question_type, question, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, sort_order, is_published, section, competency, difficulty) VALUES
(17, 'mcq', 'Amina, a Form 3 student in Garissa, hears classmates discussing a traditional ceremony involving cutting of girls. What is the correct term for procedures that involve partial or total removal of female genital organs for non-medical reasons?', 'Female genital mutilation (FGM)', 'Female circumcision surgery', 'Traditional genital therapy', 'Ritual cleansing procedure', '', 'A', 'Female genital mutilation (FGM) is the WHO-recognised term for all procedures involving partial or total removal of or injury to the female genital organs for non-medical reasons. The term female circumcision is misleading and should not be used.', 1, 1, 'pre', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Grace, a peer educator in Isiolo, is preparing a talk on FGM for her school. Which of the following are known immediate health consequences of FGM? Select ALL that apply.', 'Severe pain and bleeding', 'Urinary problems and retention', 'Increased fertility in later life', 'Serious infection and sepsis', 'Shock, which can lead to death', 'A,B,D,E', 'Immediate health consequences of FGM include severe pain, excessive bleeding, urinary problems, infection/sepsis, and shock that can result in death. FGM does NOT increase fertility — that is a harmful myth. There are no medical benefits to FGM.', 2, 1, 'pre', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Hassan, a Form 2 student in Marsabit, is told by an elder that FGM is a religious requirement in Islam. What is the correct response to this claim?', 'FGM is mandatory in Islam and is supported by the Quran', 'FGM is required by Islam only in certain counties of Kenya', 'No major religion, including Islam, mandates FGM', 'FGM is required by Christianity but not Islam', '', 'C', 'No major religion mandates FGM. Neither Islam, Christianity, nor any other widely practised faith requires FGM. Religious leaders across faiths have spoken out against the practice. This is one of the most common myths used to justify FGM.', 3, 1, 'pre', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Zawadi, a Form 4 student in Nairobi, is researching communities most affected by FGM in Kenya. Which of the following counties have some of the highest FGM prevalence rates in Kenya? Select ALL that apply.', 'Marsabit', 'Isiolo', 'Mombasa', 'Garissa', 'Samburu', 'A,B,D,E', 'According to the KDHS 2022, counties with the highest FGM prevalence include Marsabit, Isiolo, Garissa, Samburu, and Kajiado. Mombasa does not feature among the highest-prevalence counties.', 4, 1, 'pre', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Fatuma, a student in Meru, learns that FGM is illegal in Kenya. Under which law is FGM prohibited?', 'The Children Act of 2001', 'The Prohibition of Female Genital Mutilation Act of 2011', 'The Sexual Offences Act of 2006', 'The Public Health Act of 1986', '', 'B', 'FGM is illegal in Kenya under the Prohibition of Female Genital Mutilation Act of 2011. This law makes it a criminal offence to practise, procure, or promote FGM, and it is punishable by imprisonment.', 5, 1, 'pre', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'A health educator in Kisumu explains the WHO classification of FGM types. Which of the following correctly describe the four WHO types of FGM? Select ALL that apply.', 'Type I involves partial or total removal of the clitoris (clitoridectomy)', 'Type II involves removal of the clitoris and labia minora (excision)', 'Type III involves narrowing of the vaginal opening by cutting and stitching (infibulation)', 'Type IV includes all other harmful non-medical procedures to female genitalia', 'Type II involves removal of the outer skin of the abdomen', 'A,B,C,D', 'The WHO classifies FGM into four types: Type I (clitoridectomy), Type II (excision — clitoris and labia minora), Type III (infibulation — stitching to narrow the vaginal opening, the most severe type), and Type IV (all other harmful non-medical procedures). Option E is incorrect — Type II does not involve the abdomen.', 1, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Nasrin, a Form 3 student in Isiolo, asks which type of FGM is the most severe. Her teacher explains it involves stitching to narrow the vaginal opening. Which WHO type is this?', 'Type I', 'Type II', 'Type IV', 'Type III', '', 'D', 'Type III FGM, known as infibulation, is the most severe form. It involves cutting and stitching the vaginal opening leaving only a small opening for urine and menstrual flow. It causes the most serious health complications including obstructed labour.', 2, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Rehema, a peer educator in Garissa, is debunking myths about FGM. Which of the following are FALSE myths commonly used to justify FGM? Select ALL that apply.', 'FGM increases a woman''s fertility', 'FGM is required by the Islamic faith', 'FGM prevents girls from being promiscuous', 'FGM makes childbirth safer for the mother', 'FGM has no health benefits and causes only harm', 'A,B,C,D', 'Options A through D are all false myths. FGM does not increase fertility, is not required by any religion, does not prevent promiscuity, and makes childbirth more dangerous — not safer. Option E is the factual statement: FGM has no health benefits and causes serious harm.', 3, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Peter, a Form 4 student in Nakuru, learns that FGM violates several human rights. Which right is most directly violated when a girl is subjected to FGM without her consent?', 'The right to education', 'The right to vote', 'The right to bodily integrity and freedom from violence', 'The right to employment', '', 'C', 'FGM directly violates the right to bodily integrity — the right to control what happens to one''s own body — and the right to freedom from violence. It also violates the right to health, but bodily integrity is the most directly relevant right.', 4, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Miriam, a Form 2 student in Siaya, wants to report a planned FGM ceremony for her neighbour. Which of the following are valid ways to report FGM in Kenya? Select ALL that apply.', 'Call 116 (Childline Kenya)', 'Contact the nearest police station', 'Contact the local chief or assistant chief', 'Contact the Directorate of Children''s Services', 'Stay silent to avoid community conflict', 'A,B,C,D', 'FGM can be reported by calling 116 (Childline Kenya), going to the nearest police station, contacting the local chief or assistant chief, or reaching the Directorate of Children''s Services. Staying silent is never the right choice — reporting protects girls from serious harm.', 5, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Aisha, a Form 3 student in Mombasa, learns about the legal penalty for performing FGM in Kenya. A practitioner is convicted of FGM that did NOT result in death. What is the maximum prison sentence?', 'Up to 1 year imprisonment', 'Up to 5 years imprisonment', 'Up to 3 years imprisonment', 'Up to 10 years imprisonment', '', 'C', 'Under the Prohibition of Female Genital Mutilation Act 2011, a person convicted of performing FGM faces up to 3 years imprisonment. If the FGM results in the victim''s death, the penalty increases to up to 7 years imprisonment.', 6, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Brian, a male ally in Eldoret, is helping his community move away from FGM. Which of the following are effective community-level strategies to end FGM? Select ALL that apply.', 'Engaging community and religious elders in dialogue', 'Introducing alternative rites of passage that celebrate girls without cutting', 'Educating boys and men to become allies against FGM', 'Educating girls and women about their rights and the harms of FGM', 'Continuing FGM but only using sterilised equipment to reduce infection', 'A,B,C,D', 'Effective strategies include engaging elders, introducing alternative rites of passage, mobilising male allies, and educating girls about their rights. Option E is dangerously wrong — there is no safe way to perform FGM, and medicalised FGM is also prohibited by WHO and Kenyan law.', 7, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Lydia, a Form 4 student in Thika, is researching long-term health consequences of FGM. Which of the following is a recognised long-term consequence?', 'Improved sexual satisfaction due to heightened sensitivity', 'Obstructed labour and complications during childbirth', 'Reduced risk of urinary tract infections', 'Faster recovery from pregnancy', '', 'B', 'Obstructed labour is one of the most serious long-term consequences of FGM, particularly Type III. Scar tissue narrows the birth canal causing dangerous complications. Other long-term consequences include fistula, chronic pain, PTSD, and sexual dysfunction. FGM has no health benefits.', 8, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Kevin, a Form 3 student in Kisii, asks about the long-term psychological and physical effects of FGM. Which of the following are recognised long-term consequences? Select ALL that apply.', 'Post-traumatic stress disorder (PTSD)', 'Chronic pelvic pain', 'Obstetric fistula', 'Sexual dysfunction and loss of sexual pleasure', 'Increased protection against sexually transmitted infections', 'A,B,C,D', 'Long-term consequences of FGM include PTSD, chronic pelvic pain, obstetric fistula (from obstructed labour), and sexual dysfunction. FGM does NOT protect against STIs — that is a dangerous myth. All four correct options (A to D) are medically documented harms of FGM.', 9, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'According to the Kenya Demographic and Health Survey 2022, approximately what percentage of Kenyan women have undergone FGM?', 'About 5%', 'About 50%', 'About 21%', 'About 75%', '', 'C', 'The KDHS 2022 estimates approximately 21% of Kenyan women aged 15 to 49 have undergone FGM. While this represents a decline due to legal and educational efforts, FGM remains a serious public health concern especially in certain counties.', 10, 1, 'lesson', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Nasrin in Isiolo describes a procedure where only the clitoral hood was removed but the clitoris itself is intact. Which WHO type does this fall under?', 'Type II', 'Type III', 'Type I', 'Type IV', '', 'C', 'Type I FGM (clitoridectomy) includes partial or total removal of the clitoris and/or the prepuce (clitoral hood). Even partial removal of the clitoral hood falls under Type I. Type II involves the labia, Type III involves stitching, and Type IV covers other harmful procedures.', 1, 1, 'post', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Nasrin''s younger sister in Isiolo is at risk of FGM. Which of the following actions would be appropriate for Nasrin to take? Select ALL that apply.', 'Call 116 (Childline Kenya) to report the threat', 'Inform a trusted teacher or school counsellor', 'Contact the local assistant chief for intervention', 'Reach out to the Directorate of Children''s Services', 'Keep quiet to respect cultural traditions and avoid conflict', 'A,B,C,D', 'When a girl is at risk of FGM, appropriate actions include calling Childline (116), informing a trusted adult at school, contacting the local chief, or reaching the Directorate of Children''s Services. Staying silent allows harm to happen and contravenes the duty to report under the Prohibition of FGM Act 2011.', 2, 1, 'post', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'A community health worker in Marsabit is counselling a family who believe FGM will improve their daughter''s marriage prospects. What is the most accurate and rights-based response?', 'FGM may be acceptable if the girl consents when she is older', 'FGM is illegal in Kenya, causes serious health harm, and violates the girl''s rights — there are no health benefits', 'FGM is only harmful if performed by untrained practitioners, so a medical professional should do it instead', 'FGM is a cultural matter and health workers should not interfere', '', 'B', 'FGM is illegal under the Prohibition of FGM Act 2011, causes serious health harm with no medical benefits, and violates a girl''s rights to health, bodily integrity, and freedom from violence. Medicalised FGM is also illegal and condemned by the WHO — it does not reduce the harm.', 3, 1, 'post', 'fgm_gbv', 'MEDIUM'),
(17, 'msq', 'Rehema is a peer educator in Garissa explaining why FGM violates human rights. Which of the following rights does FGM violate? Select ALL that apply.', 'The right to health', 'The right to bodily integrity', 'The right to freedom from violence and torture', 'The right to life (when FGM causes death)', 'The right to practise harmful cultural traditions without legal consequence', 'A,B,C,D', 'FGM violates the right to health (causes serious harm), bodily integrity (performed without meaningful consent), freedom from violence, and the right to life when it results in death. Option E is false — harmful cultural practices do not override the law or human rights under the Constitution of Kenya 2010 or the Prohibition of FGM Act 2011.', 4, 1, 'post', 'fgm_gbv', 'MEDIUM'),
(17, 'mcq', 'Grace, a Form 4 student in Kisumu, is asked: what is the single most important reason why alternative rites of passage are promoted in communities where FGM has been practised? What is the best answer?', 'They allow communities to abandon all cultural practices entirely', 'They celebrate girls'' transition to adulthood while preserving cultural identity without causing physical harm', 'They are cheaper than traditional FGM ceremonies', 'They are required by the Kenyan government for all communities', '', 'B', 'Alternative rites of passage are promoted because they allow communities to celebrate a girl''s transition to womanhood and preserve cultural identity while removing the harmful cutting element. This approach respects culture while protecting girls'' health and rights, making community acceptance more likely.', 5, 1, 'post', 'fgm_gbv', 'MEDIUM');";
    $db->exec($sql);
    $steps[] = "Step 2: Inserted 20 module 17 FGM/GBV quiz questions ✓";
} else {
    $steps[] = "Step 2: Module 17 questions already exist ($existing17 found, skipped)";
}

$db->close();
echo "<pre>\n";
foreach ($steps as $s) echo $s . "\n";
echo "\nALL DONE\n</pre>";
unlink(__FILE__);
