#!/usr/bin/env bash
# =============================================================================
# ARISE — one-shot updater installer for field boxes that don't have it yet.
#
# What this does (idempotently — safe to re-run):
#   1. Locates the ARISE install (via --arise-root or common defaults).
#   2. Configures git remote + tracking branch (default: field-boxes).
#   3. Installs /usr/local/bin/arise-update  (the daily updater).
#   4. Installs /etc/cron.d/arise-update     (runs 03:00 local time daily).
#   5. Seeds the migration-tracking file with every migrate_*.php currently
#      in the repo — those are already-applied, so the updater skips them
#      on first run and only applies NEW migrations that arrive via git.
#   6. Creates /var/lib/arise/ (state) and /var/log/arise-update.log.
#
# Usage (run on the box as root):
#   sudo bash install-updater.sh                       # auto-detect ARISE root
#   sudo bash install-updater.sh --arise-root /var/www/arise
#   sudo bash install-updater.sh --branch field-boxes  # default already
#   sudo bash install-updater.sh --dry-run             # print, don't act
#
# After install, run one manual update to verify:
#   sudo arise-update --now
# =============================================================================
set -euo pipefail

ARISE_ROOT=""
BRANCH="field-boxes"
REMOTE_URL="https://github.com/kenyaone/arise.git"
DRY_RUN=0
OFFLINE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --arise-root) ARISE_ROOT="$2"; shift 2 ;;
        --branch)     BRANCH="$2";     shift 2 ;;
        --remote)     REMOTE_URL="$2"; shift 2 ;;
        --dry-run)    DRY_RUN=1;       shift   ;;
        --offline)    OFFLINE=1;       shift   ;;
        -h|--help)
            sed -n '2,26p' "$0"; exit 0 ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
done

log()  { printf '[install-updater %(%F %T)T] %s\n' -1 "$*"; }
run()  { if (( DRY_RUN )); then echo "  DRY: $*"; else eval "$@"; fi; }
fail() { echo "ERROR: $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || fail "must run as root (sudo)"

# ── 1. Find ARISE root ──────────────────────────────────────────────────────
if [[ -z "$ARISE_ROOT" ]]; then
    for candidate in \
        /var/www/arise /var/www/html/arise /srv/arise \
        /home/arise/public_html /home/*/arise
    do
        if [[ -d "$candidate/.git" && -d "$candidate/public" && -d "$candidate/data" ]]; then
            ARISE_ROOT="$candidate"; break
        fi
    done
fi
[[ -n "$ARISE_ROOT" && -d "$ARISE_ROOT/.git" ]] || \
    fail "could not locate ARISE install — pass --arise-root /path/to/arise"
log "ARISE_ROOT=$ARISE_ROOT"

cd "$ARISE_ROOT"

# ── 2. Configure git remote + branch ────────────────────────────────────────
if ! git remote get-url origin >/dev/null 2>&1; then
    log "adding origin remote → $REMOTE_URL"
    run "git remote add origin '$REMOTE_URL'"
fi
if (( OFFLINE )); then
    log "offline mode — skipping 'git fetch origin' (assumes working tree already updated)"
else
    if ! run "git fetch --prune origin"; then
        log "WARNING: git fetch failed — continuing with local tree only"
    fi
fi

# Only switch branches if we can — offline boxes may not have origin/$BRANCH
if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH"; then
    if ! git show-ref --verify --quiet "refs/heads/$BRANCH"; then
        log "creating local branch $BRANCH tracking origin/$BRANCH"
        run "git checkout -B '$BRANCH' 'origin/$BRANCH'"
    elif [[ "$(git symbolic-ref --short HEAD 2>/dev/null || echo)" != "$BRANCH" ]]; then
        log "switching to $BRANCH"
        run "git checkout '$BRANCH'"
    fi
else
    log "no origin/$BRANCH ref locally (offline?) — leaving current branch alone"
fi

# ── 3. State + log dirs ─────────────────────────────────────────────────────
run "install -d -m 0755 /var/lib/arise"
run "install -d -m 0755 /var/backups/arise"
run "touch /var/log/arise-update.log"
run "chmod 0644 /var/log/arise-update.log"

# ── 4. Seed applied-migrations from currently-present files ─────────────────
APPLIED="/var/lib/arise/applied-migrations.txt"
if [[ ! -f "$APPLIED" ]]; then
    log "seeding $APPLIED with all migrate_*.php files currently in repo"
    if (( DRY_RUN )); then
        echo "  DRY: would seed $(ls migrate_*.php 2>/dev/null | wc -l) migration filenames"
    else
        ( cd "$ARISE_ROOT" && ls migrate_*.php 2>/dev/null | sort > "$APPLIED" ) || true
        chmod 0644 "$APPLIED"
    fi
else
    log "$APPLIED already exists — leaving alone"
fi

# ── 5. Persist the updater config so arise-update knows where to work ──────
CONF="/etc/arise-update.conf"
log "writing config → $CONF"
if (( DRY_RUN )); then
    echo "  DRY: would write $CONF"
else
    cat > "$CONF" <<EOF
# Generated by install-updater.sh — safe to hand-edit.
ARISE_ROOT="$ARISE_ROOT"
ARISE_BRANCH="$BRANCH"
ARISE_DB="\$ARISE_ROOT/data/arise.db"
ARISE_BACKUP_DIR="/var/backups/arise"
ARISE_APPLIED_FILE="/var/lib/arise/applied-migrations.txt"
ARISE_LOG="/var/log/arise-update.log"
ARISE_HEARTBEAT_URL=""   # optional; leave blank to disable heartbeat POST
EOF
    chmod 0644 "$CONF"
fi

# ── 6. Install arise-update binary ──────────────────────────────────────────
SRC="$ARISE_ROOT/deploy/arise-update.sh"
DEST="/usr/local/bin/arise-update"
[[ -f "$SRC" ]] || fail "expected updater script not found: $SRC — is the repo up to date?"
log "installing $DEST"
run "install -m 0755 '$SRC' '$DEST'"

# ── 7. Install cron job ─────────────────────────────────────────────────────
CRON="/etc/cron.d/arise-update"
log "installing cron → $CRON (daily 03:00 local time)"
if (( DRY_RUN )); then
    echo "  DRY: would write $CRON"
else
    cat > "$CRON" <<'EOF'
# ARISE daily updater. Runs at 03:00 local time. Output goes to /var/log/arise-update.log.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
0 3 * * * root /usr/local/bin/arise-update >>/var/log/arise-update.log 2>&1
EOF
    chmod 0644 "$CRON"
fi

# ── 8. Logrotate ────────────────────────────────────────────────────────────
LR="/etc/logrotate.d/arise-update"
log "installing logrotate → $LR"
if (( DRY_RUN )); then
    echo "  DRY: would write $LR"
else
    cat > "$LR" <<'EOF'
/var/log/arise-update.log {
    weekly
    rotate 12
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
}
EOF
    chmod 0644 "$LR"
fi

log "DONE."
cat <<EOF

Next steps:
  1. Run one update to verify everything works:
       sudo arise-update --now
  2. Tail the log during/after:
       tail -f /var/log/arise-update.log
  3. (Optional) enable heartbeat reporting by editing $CONF and setting
     ARISE_HEARTBEAT_URL to your cloud endpoint (e.g. https://ariseci.org/arise-heartbeat.php).

EOF
